In [1]:
#Imported the Necessary Packages
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
#Loading the Datasets
building=pd.read_csv('C:/Users/leepa/Documents/data_center_energy_prediction/data/raw/building_metadata.csv')
building

,site_id,building_id,primary_use,square_feet,year_built,floor_count
0,0,0,Education,7432,2008.0,NaN
1,0,1,Education,2720,2004.0,NaN
2,0,2,Education,5376,1991.0,NaN
3,0,3,Education,23685,2002.0,NaN
4,0,4,Education,116607,1975.0,NaN
...,...,...,...,...,...,...
1444,15,1444,Entertainment/public assembly,19619,1914.0,NaN
1445,15,1445,Education,4298,NaN,NaN
1446,15,1446,Entertainment/public assembly,11265,1997.0,NaN
1447,15,1447,Lodging/residential,29775,2001.0,NaN
1448,15,1448,Office,92271,2001.0,NaN

In [3]:
energy=pd.read_csv(r'C:\Users\leepa\Documents\data_center_energy_prediction\data\raw\energy_usage.csv')
energy

###OUTPUT TABLE VALUE METER READING###

          building_id  meter            timestamp  meter_reading
0                   0      0  2016-01-01 00:00:00          0.000
1                   1      0  2016-01-01 00:00:00          0.000
2                   2      0  2016-01-01 00:00:00          0.000
3                   3      0  2016-01-01 00:00:00          0.000
4                   4      0  2016-01-01 00:00:00          0.000
...               ...    ...                  ...            ...
20216095         1444      0  2016-12-31 23:00:00          8.750
20216096         1445      0  2016-12-31 23:00:00          4.825
20216097         1446      0  2016-12-31 23:00:00          0.000
20216098         1447      0  2016-12-31 23:00:00        159.575
20216099         1448      0  2016-12-31 23:00:00          2.850

[20216100 rows x 4 columns]

In [4]:
weather=pd.read_csv(r'C:\Users\leepa\Documents\data_center_energy_prediction\data\raw\weather_train.csv')
weather

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,0,2016-01-01 01:00:00,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,0,2016-01-01 02:00:00,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,0,2016-01-01 03:00:00,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,0,2016-01-01 04:00:00,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6
...,...,...,...,...,...,...,...,...,...
139768,15,2016-12-31 19:00:00,3.0,NaN,-8.0,NaN,NaN,180.0,5.7
139769,15,2016-12-31 20:00:00,2.8,2.0,-8.9,NaN,1007.4,180.0,7.7
139770,15,2016-12-31 21:00:00,2.8,NaN,-7.2,NaN,1007.5,180.0,5.1
139771,15,2016-12-31 22:00:00,2.2,NaN,-6.7,NaN,1008.0,170.0,4.6
139772,15,2016-12-31 23:00:00,1.7,NaN,-5.6,-1.0,1008.5,180.0,8.8

In [5]:
#Exploring the Datasets via 
energy.shape

(20216100, 4)

In [6]:
energy.describe()

        building_id         meter  meter_reading
count  2.021610e+07  2.021610e+07   2.021610e+07
mean   7.992780e+02  6.624412e-01   2.117121e+03
std    4.269133e+02  9.309921e-01   1.532356e+05
min    0.000000e+00  0.000000e+00   0.000000e+00
25%    3.930000e+02  0.000000e+00   1.830000e+01
50%    8.950000e+02  0.000000e+00   7.877500e+01
75%    1.179000e+03  1.000000e+00   2.679840e+02
max    1.448000e+03  3.000000e+00   2.190470e+07

In [7]:
energy.size

80864400

In [8]:
energy.tail()

          building_id  meter            timestamp  meter_reading
20216095         1444      0  2016-12-31 23:00:00          8.750
20216096         1445      0  2016-12-31 23:00:00          4.825
20216097         1446      0  2016-12-31 23:00:00          0.000
20216098         1447      0  2016-12-31 23:00:00        159.575
20216099         1448      0  2016-12-31 23:00:00          2.850

In [9]:
energy.head()

   building_id  meter            timestamp  meter_reading
0            0      0  2016-01-01 00:00:00            0.0
1            1      0  2016-01-01 00:00:00            0.0
2            2      0  2016-01-01 00:00:00            0.0
3            3      0  2016-01-01 00:00:00            0.0
4            4      0  2016-01-01 00:00:00            0.0

In [10]:
energy.shape

(20216100, 4)

In [11]:
energy.value_counts()

building_id  meter  timestamp            meter_reading
0            0      2016-01-01 00:00:00  0.000            1
1            0      2016-01-01 00:00:00  0.000            1
2            0      2016-01-01 00:00:00  0.000            1
3            0      2016-01-01 00:00:00  0.000            1
4            0      2016-01-01 00:00:00  0.000            1
                                                         ..
1444         0      2016-12-31 23:00:00  8.750            1
1445         0      2016-12-31 23:00:00  4.825            1
1446         0      2016-12-31 23:00:00  0.000            1
1447         0      2016-12-31 23:00:00  159.575          1
1448         0      2016-12-31 23:00:00  2.850            1
Name: count, Length: 20216100, dtype: int64

In [12]:
energy.describe

<bound method NDFrame.describe of           building_id  meter            timestamp  meter_reading
0                   0      0  2016-01-01 00:00:00          0.000
1                   1      0  2016-01-01 00:00:00          0.000
2                   2      0  2016-01-01 00:00:00          0.000
3                   3      0  2016-01-01 00:00:00          0.000
4                   4      0  2016-01-01 00:00:00          0.000
...               ...    ...                  ...            ...
20216095         1444      0  2016-12-31 23:00:00          8.750
20216096         1445      0  2016-12-31 23:00:00          4.825
20216097         1446      0  2016-12-31 23:00:00          0.000
20216098         1447      0  2016-12-31 23:00:00        159.575
20216099         1448      0  2016-12-31 23:00:00          2.850

[20216100 rows x 4 columns]>

In [13]:
building.size

8694

In [14]:
building.shape

(1449, 6)

In [15]:
building.describe

<bound method NDFrame.describe of       site_id  building_id                    primary_use  square_feet  \
0           0            0                      Education         7432
1           0            1                      Education         2720
2           0            2                      Education         5376
3           0            3                      Education        23685
4           0            4                      Education       116607
...       ...          ...                            ...          ...
1444       15         1444  Entertainment/public assembly        19619
1445       15         1445                      Education         4298
1446       15         1446  Entertainment/public assembly        11265
1447       15         1447            Lodging/residential        29775
1448       15         1448                         Office        92271

      year_built  floor_count
0         2008.0          NaN
1         2004.0          NaN
2         1991.0          NaN
3         2002.0          NaN
4         1975.0          NaN
...          ...          ...
1444      1914.0          NaN
1445         NaN          NaN
1446      1997.0          NaN
1447      2001.0          NaN
1448      2001.0          NaN

[1449 rows x 6 columns]>

In [16]:
building.value_counts

<bound method DataFrame.value_counts of       site_id  building_id                    primary_use  square_feet  \
0           0            0                      Education         7432
1           0            1                      Education         2720
2           0            2                      Education         5376
3           0            3                      Education        23685
4           0            4                      Education       116607
...       ...          ...                            ...          ...
1444       15         1444  Entertainment/public assembly        19619
1445       15         1445                      Education         4298
1446       15         1446  Entertainment/public assembly        11265
1447       15         1447            Lodging/residential        29775
1448       15         1448                         Office        92271

      year_built  floor_count
0         2008.0          NaN
1         2004.0          NaN
2         1991.0          NaN
3         2002.0          NaN
4         1975.0          NaN
...          ...          ...
1444      1914.0          NaN
1445         NaN          NaN
1446      1997.0          NaN
1447      2001.0          NaN
1448      2001.0          NaN

[1449 rows x 6 columns]>

In [17]:
building.head()

   site_id  building_id primary_use  square_feet  year_built  floor_count
0        0            0   Education         7432      2008.0          NaN
1        0            1   Education         2720      2004.0          NaN
2        0            2   Education         5376      1991.0          NaN
3        0            3   Education        23685      2002.0          NaN
4        0            4   Education       116607      1975.0          NaN

In [18]:
building.tail()

,site_id,building_id,primary_use,square_feet,year_built,floor_count
1444,15,1444,Entertainment/public assembly,19619,1914.0,NaN
1445,15,1445,Education,4298,NaN,NaN
1446,15,1446,Entertainment/public assembly,11265,1997.0,NaN
1447,15,1447,Lodging/residential,29775,2001.0,NaN
1448,15,1448,Office,92271,2001.0,NaN

In [19]:
weather.head()

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,0,2016-01-01 01:00:00,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,0,2016-01-01 02:00:00,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,0,2016-01-01 03:00:00,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,0,2016-01-01 04:00:00,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6

In [20]:
weather.tail()

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
139768,15,2016-12-31 19:00:00,3.0,NaN,-8.0,NaN,NaN,180.0,5.7
139769,15,2016-12-31 20:00:00,2.8,2.0,-8.9,NaN,1007.4,180.0,7.7
139770,15,2016-12-31 21:00:00,2.8,NaN,-7.2,NaN,1007.5,180.0,5.1
139771,15,2016-12-31 22:00:00,2.2,NaN,-6.7,NaN,1008.0,170.0,4.6
139772,15,2016-12-31 23:00:00,1.7,NaN,-5.6,-1.0,1008.5,180.0,8.8

In [21]:
weather.shape

(139773, 9)

In [22]:
weather.size

1257957

In [23]:
weather.describe()

,site_id,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
count,139773.000000,139718.000000,70600.000000,139660.000000,89484.000000,129155.000000,133505.000000,139469.000000
mean,7.478977,14.418106,2.149306,7.350158,0.983047,1016.158038,180.526632,3.560527
std,4.604744,10.626595,2.599150,9.790235,8.463678,7.629684,111.523629,2.335874
min,0.000000,-28.900000,0.000000,-35.000000,-1.000000,968.200000,0.000000,0.000000
25%,3.000000,7.200000,0.000000,0.600000,0.000000,1011.800000,80.000000,2.100000
50%,7.000000,15.000000,2.000000,8.300000,0.000000,1016.400000,190.000000,3.100000
75%,11.000000,22.200000,4.000000,14.400000,0.000000,1020.800000,280.000000,5.000000
max,15.000000,47.200000,9.000000,26.100000,343.000000,1045.500000,360.000000,19.000000

In [24]:
weather.columns

Index(['site_id', 'timestamp', 'air_temperature', 'cloud_coverage',
       'dew_temperature', 'precip_depth_1_hr', 'sea_level_pressure',
       'wind_direction', 'wind_speed'],
      dtype='str')

In [25]:
energy.columns

Index(['building_id', 'meter', 'timestamp', 'meter_reading'], dtype='str')

In [26]:
building.columns

Index(['site_id', 'building_id', 'primary_use', 'square_feet', 'year_built',
       'floor_count'],
      dtype='str')

In [27]:
energy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20216100 entries, 0 to 20216099
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   building_id    int64
 1   meter          int64
 2   timestamp      str
 3   meter_reading  float64
dtypes: float64(1), int64(2), str(1)
memory usage: 616.9 MB

In [28]:
building.info()

<class 'pandas.DataFrame'>
RangeIndex: 1449 entries, 0 to 1448
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site_id      1449 non-null   int64
 1   building_id  1449 non-null   int64
 2   primary_use  1449 non-null   str
 3   square_feet  1449 non-null   int64
 4   year_built   675 non-null    float64
 5   floor_count  355 non-null    float64
dtypes: float64(2), int64(3), str(1)
memory usage: 68.1 KB

In [29]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 139773 entries, 0 to 139772
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   site_id             139773 non-null  int64
 1   timestamp           139773 non-null  str
 2   air_temperature     139718 non-null  float64
 3   cloud_coverage      70600 non-null   float64
 4   dew_temperature     139660 non-null  float64
 5   precip_depth_1_hr   89484 non-null   float64
 6   sea_level_pressure  129155 non-null  float64
 7   wind_direction      133505 non-null  float64
 8   wind_speed          139469 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 9.6 MB

In [30]:
#Beginning to Merge the Datasets, the earlier steps of data preprocessing

energy['timestamp']=pd.to_datetime(energy['timestamp'])
weather['timestamp']=pd.to_datetime(energy['timestamp'])

In [31]:
energy

          building_id  meter           timestamp  meter_reading
0                   0      0 2016-01-01 00:00:00          0.000
1                   1      0 2016-01-01 00:00:00          0.000
2                   2      0 2016-01-01 00:00:00          0.000
3                   3      0 2016-01-01 00:00:00          0.000
4                   4      0 2016-01-01 00:00:00          0.000
...               ...    ...                 ...            ...
20216095         1444      0 2016-12-31 23:00:00          8.750
20216096         1445      0 2016-12-31 23:00:00          4.825
20216097         1446      0 2016-12-31 23:00:00          0.000
20216098         1447      0 2016-12-31 23:00:00        159.575
20216099         1448      0 2016-12-31 23:00:00          2.850

[20216100 rows x 4 columns]

In [32]:
building

,site_id,building_id,primary_use,square_feet,year_built,floor_count
0,0,0,Education,7432,2008.0,NaN
1,0,1,Education,2720,2004.0,NaN
2,0,2,Education,5376,1991.0,NaN
3,0,3,Education,23685,2002.0,NaN
4,0,4,Education,116607,1975.0,NaN
...,...,...,...,...,...,...
1444,15,1444,Entertainment/public assembly,19619,1914.0,NaN
1445,15,1445,Education,4298,NaN,NaN
1446,15,1446,Entertainment/public assembly,11265,1997.0,NaN
1447,15,1447,Lodging/residential,29775,2001.0,NaN
1448,15,1448,Office,92271,2001.0,NaN

In [33]:
weather

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,0,2016-01-01 00:00:00,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,0,2016-01-01 00:00:00,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,0,2016-01-01 00:00:00,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,0,2016-01-01 00:00:00,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6
...,...,...,...,...,...,...,...,...,...
139768,15,2016-01-03 12:00:00,3.0,NaN,-8.0,NaN,NaN,180.0,5.7
139769,15,2016-01-03 12:00:00,2.8,2.0,-8.9,NaN,1007.4,180.0,7.7
139770,15,2016-01-03 12:00:00,2.8,NaN,-7.2,NaN,1007.5,180.0,5.1
139771,15,2016-01-03 12:00:00,2.2,NaN,-6.7,NaN,1008.0,170.0,4.6
139772,15,2016-01-03 12:00:00,1.7,NaN,-5.6,-1.0,1008.5,180.0,8.8

In [34]:
energy.columns

Index(['building_id', 'meter', 'timestamp', 'meter_reading'], dtype='str')

In [35]:
weather.columns

Index(['site_id', 'timestamp', 'air_temperature', 'cloud_coverage',
       'dew_temperature', 'precip_depth_1_hr', 'sea_level_pressure',
       'wind_direction', 'wind_speed'],
      dtype='str')

In [36]:
building.columns

Index(['site_id', 'building_id', 'primary_use', 'square_feet', 'year_built',
       'floor_count'],
      dtype='str')

In [37]:
#Now we are initializing to merge all the datasets together

In [38]:

dfmerge=energy.merge(building,on=['building_id',],how='left')
dfmerge

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count
0,0,0,2016-01-01 00:00:00,0.000,0,Education,7432,2008.0,NaN
1,1,0,2016-01-01 00:00:00,0.000,0,Education,2720,2004.0,NaN
2,2,0,2016-01-01 00:00:00,0.000,0,Education,5376,1991.0,NaN
3,3,0,2016-01-01 00:00:00,0.000,0,Education,23685,2002.0,NaN
4,4,0,2016-01-01 00:00:00,0.000,0,Education,116607,1975.0,NaN
...,...,...,...,...,...,...,...,...,...
20216095,1444,0,2016-12-31 23:00:00,8.750,15,Entertainment/public assembly,19619,1914.0,NaN
20216096,1445,0,2016-12-31 23:00:00,4.825,15,Education,4298,NaN,NaN
20216097,1446,0,2016-12-31 23:00:00,0.000,15,Entertainment/public assembly,11265,1997.0,NaN
20216098,1447,0,2016-12-31 23:00:00,159.575,15,Lodging/residential,29775,2001.0,NaN
20216099,1448,0,2016-12-31 23:00:00,2.850,15,Office,92271,2001.0,NaN

In [39]:
#Now merge total dataset
# 8GB laptop HP couldnt handle such a huge data so we are reducing the columns 
# ERROR 
# File pandas/_libs/join.pyx:117, in pandas._libs.join.left_outer_join()
# MemoryError: Unable to allocate 307. MiB for an array with shape (40289271,) and data type int64




# Cell In[243], line 6
#       1 #Choosing the necessary columnd from weather_small to merge and produce the final dataset
#       3 weather_columns=['site_id','timestamp','air_temperature','cloud_coverage','dew_temperature','precip_depth_1_hr','sea_level_pressure','wind_direction','wind_speed']
# ----> 6 fdf=df.merge(weather_small[weather_columns],on=['site_id','timestamp'],how='left')

# File c:\Users\leepa\Documents\data_center_energy_prediction\venv\lib\site-packages\pandas\core\frame.py:10859, in DataFrame.merge(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
#   10840 @Substitution("")
#   10841 @Appender(_merge_doc, indents=2)
#   10842 def merge(
#    (...)
#   10855     validate: MergeValidate | None = None,
#   10856 ) -> DataFrame:
#   10857     from pandas.core.reshape.merge import merge
# > 10859     return merge(
#   10860         self,
#   10861         right,
#   10862         how=how,
#   10863         on=on,
#   10864         left_on=left_on,
#   10865         right_on=right_on,
#   10866         left_index=left_index,
#   10867         right_index=right_index,
#   10868         sort=sort,
# ...
#     290 if not isinstance(arrs, tuple):
#     291     arrs = (arrs,)
# --> 292 return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)

# MemoryError: Unable to allocate 922. MiB for an array with shape (3, 40289271) and data type float64

In [40]:
dfmerge.columns

Index(['building_id', 'meter', 'timestamp', 'meter_reading', 'site_id',
       'primary_use', 'square_feet', 'year_built', 'floor_count'],
      dtype='str')

In [41]:
building_keep=dfmerge['building_id'].unique()[:16]

In [42]:
energy_small=energy[(energy['building_id'].isin(building_keep))& (energy['timestamp']<'2016-04-01')]

In [43]:
weather_small=weather[(weather['site_id'].isin(building_keep))& (weather['timestamp']<'2016-04-01')]

In [44]:
energy_small

         building_id  meter           timestamp  meter_reading
0                  0      0 2016-01-01 00:00:00           0.00
1                  1      0 2016-01-01 00:00:00           0.00
2                  2      0 2016-01-01 00:00:00           0.00
3                  3      0 2016-01-01 00:00:00           0.00
4                  4      0 2016-01-01 00:00:00           0.00
...              ...    ...                 ...            ...
4776824           13      1 2016-03-31 23:00:00           0.00
4776825           14      0 2016-03-31 23:00:00           0.00
4776826           14      1 2016-03-31 23:00:00        1603.99
4776827           15      0 2016-03-31 23:00:00           0.00
4776828           15      1 2016-03-31 23:00:00        1139.68

[38739 rows x 4 columns]

In [45]:
building_keep

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
dfmerge

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count
0,0,0,2016-01-01 00:00:00,0.000,0,Education,7432,2008.0,NaN
1,1,0,2016-01-01 00:00:00,0.000,0,Education,2720,2004.0,NaN
2,2,0,2016-01-01 00:00:00,0.000,0,Education,5376,1991.0,NaN
3,3,0,2016-01-01 00:00:00,0.000,0,Education,23685,2002.0,NaN
4,4,0,2016-01-01 00:00:00,0.000,0,Education,116607,1975.0,NaN
...,...,...,...,...,...,...,...,...,...
20216095,1444,0,2016-12-31 23:00:00,8.750,15,Entertainment/public assembly,19619,1914.0,NaN
20216096,1445,0,2016-12-31 23:00:00,4.825,15,Education,4298,NaN,NaN
20216097,1446,0,2016-12-31 23:00:00,0.000,15,Entertainment/public assembly,11265,1997.0,NaN
20216098,1447,0,2016-12-31 23:00:00,159.575,15,Lodging/residential,29775,2001.0,NaN
20216099,1448,0,2016-12-31 23:00:00,2.850,15,Office,92271,2001.0,NaN

In [47]:
# df_optimized=df.groupby('building_id',group_keys=False).apply(lambda x: x.sample(frac=0.1,random_state=42))
df_optimized=dfmerge.sample(n=65000,random_state=42)

In [48]:
df_optimized

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count
14245562,1324,1,2016-09-16 16:00:00,0.0000,14,Entertainment/public assembly,84688,NaN,NaN
1282718,1013,0,2016-01-24 06:00:00,32.0001,10,Education,67377,NaN,3.0
13883790,229,1,2016-09-10 07:00:00,567.6550,2,Education,140092,NaN,NaN
4781820,217,3,2016-04-01 01:00:00,0.0000,2,Education,282946,2003.0,NaN
10415393,1434,0,2016-07-10 04:00:00,65.7500,15,Education,33148,1967.0,NaN
...,...,...,...,...,...,...,...,...,...
19744765,834,0,2016-12-23 16:00:00,18.7500,8,Public services,4934,NaN,1.0
1355091,1418,2,2016-01-25 13:00:00,936.3470,15,Lodging/residential,41302,1975.0,NaN
15677496,887,0,2016-10-12 00:00:00,71.0000,9,Lodging/residential,69754,NaN,NaN
2662370,346,0,2016-02-19 03:00:00,34.3900,3,Entertainment/public assembly,17709,NaN,NaN
10603155,1386,0,2016-07-13 12:00:00,127.7750,15,Entertainment/public assembly,82035,1975.0,NaN

In [49]:
weather_small

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,0,2016-01-01 00:00:00,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,0,2016-01-01 00:00:00,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,0,2016-01-01 00:00:00,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,0,2016-01-01 00:00:00,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6
...,...,...,...,...,...,...,...,...,...
139768,15,2016-01-03 12:00:00,3.0,NaN,-8.0,NaN,NaN,180.0,5.7
139769,15,2016-01-03 12:00:00,2.8,2.0,-8.9,NaN,1007.4,180.0,7.7
139770,15,2016-01-03 12:00:00,2.8,NaN,-7.2,NaN,1007.5,180.0,5.1
139771,15,2016-01-03 12:00:00,2.2,NaN,-6.7,NaN,1008.0,170.0,4.6
139772,15,2016-01-03 12:00:00,1.7,NaN,-5.6,-1.0,1008.5,180.0,8.8

In [50]:
#Choosing the necessary columnd from weather_small to merge and produce the final dataset

weather_columns=['site_id','timestamp','air_temperature','cloud_coverage','dew_temperature','precip_depth_1_hr','sea_level_pressure','wind_direction','wind_speed']


df=df_optimized.merge(weather_small[weather_columns],on=['site_id','timestamp'],how='left')

In [51]:
df

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,1324,1,2016-09-16 16:00:00,0.0000,14,Entertainment/public assembly,84688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1013,0,2016-01-24 06:00:00,32.0001,10,Education,67377,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,229,1,2016-09-10 07:00:00,567.6550,2,Education,140092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,217,3,2016-04-01 01:00:00,0.0000,2,Education,282946,2003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1434,0,2016-07-10 04:00:00,65.7500,15,Education,33148,1967.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146006,834,0,2016-12-23 16:00:00,18.7500,8,Public services,4934,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146007,1418,2,2016-01-25 13:00:00,936.3470,15,Lodging/residential,41302,1975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146008,887,0,2016-10-12 00:00:00,71.0000,9,Lodging/residential,69754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146009,346,0,2016-02-19 03:00:00,34.3900,3,Entertainment/public assembly,17709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146010,1386,0,2016-07-13 12:00:00,127.7750,15,Entertainment/public assembly,82035,1975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df=df.sort_values(by=['building_id','timestamp']).reset_index(drop=True)
df

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,0,2016-01-26 16:00:00,0.000,0,Education,7432,2008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,2016-01-26 23:00:00,0.000,0,Education,7432,2008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,2016-02-17 21:00:00,0.000,0,Education,7432,2008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,2016-02-21 15:00:00,0.000,0,Education,7432,2008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,2016-03-03 00:00:00,0.000,0,Education,7432,2008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146006,1448,0,2016-11-22 21:00:00,3.100,15,Office,92271,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146007,1448,0,2016-11-30 02:00:00,3.375,15,Office,92271,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146008,1448,0,2016-12-08 08:00:00,4.275,15,Office,92271,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146009,1448,0,2016-12-16 23:00:00,3.125,15,Office,92271,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146010,1448,0,2016-12-18 23:00:00,3.775,15,Office,92271,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
#Checking for missing values
df.isna().sum()

building_id                0
meter                      0
timestamp                  0
meter_reading              0
site_id                    0
primary_use                0
square_feet                0
year_built             82425
floor_count           123112
air_temperature        64977
cloud_coverage         99224
dew_temperature        64994
precip_depth_1_hr      81403
sea_level_pressure     70349
wind_direction         69859
wind_speed             65150
dtype: int64

In [54]:
#Filling the Missing Values for year_built
df['year_built']=df['year_built'].fillna(df['year_built'].median())
df.isna().sum()

building_id                0
meter                      0
timestamp                  0
meter_reading              0
site_id                    0
primary_use                0
square_feet                0
year_built                 0
floor_count           123112
air_temperature        64977
cloud_coverage         99224
dew_temperature        64994
precip_depth_1_hr      81403
sea_level_pressure     70349
wind_direction         69859
wind_speed             65150
dtype: int64

In [55]:
df['air_temperature']=df['air_temperature'].fillna(df['air_temperature'].median())

In [56]:
df['cloud_coverage']=df['cloud_coverage'].fillna(df['cloud_coverage'].median())

In [57]:
df['dew_temperature']=df['dew_temperature'].fillna(df['dew_temperature'].median())

In [58]:
df['precip_depth_1_hr']=df['precip_depth_1_hr'].fillna(0)

In [59]:
df['sea_level_pressure']=df['sea_level_pressure'].fillna(df['sea_level_pressure'].median())

In [60]:
df['wind_direction']=df['wind_direction'].fillna(df['wind_direction'].median())

In [61]:
df['wind_speed']=df['wind_speed'].fillna(df['wind_speed'].median())

In [62]:
df.isna().sum()

building_id                0
meter                      0
timestamp                  0
meter_reading              0
site_id                    0
primary_use                0
square_feet                0
year_built                 0
floor_count           123112
air_temperature            0
cloud_coverage             0
dew_temperature            0
precip_depth_1_hr          0
sea_level_pressure         0
wind_direction             0
wind_speed                 0
dtype: int64

In [63]:
##Floor count is having large number of errors or missing values so drop
#drop floor

df=df.drop(columns=['floor_count'])

In [64]:
df.isna().sum()

building_id           0
meter                 0
timestamp             0
meter_reading         0
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
dtype: int64

In [65]:
####################
####################



# CLEARED ALL THE MISSING VALUES AND READY FOR FEATURE ENGINEERING

####################
####################

In [66]:
df.shape
df

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,0,2016-01-26 16:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
1,0,0,2016-01-26 23:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
2,0,0,2016-02-17 21:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
3,0,0,2016-02-21 15:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
4,0,0,2016-03-03 00:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146006,1448,0,2016-11-22 21:00:00,3.100,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146007,1448,0,2016-11-30 02:00:00,3.375,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146008,1448,0,2016-12-08 08:00:00,4.275,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146009,1448,0,2016-12-16 23:00:00,3.125,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146010,1448,0,2016-12-18 23:00:00,3.775,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1

In [67]:
df.tail(100)

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
145911,1444,0,2016-09-11 01:00:00,7.450,15,Entertainment/public assembly,19619,1914.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
145912,1444,0,2016-10-11 02:00:00,8.175,15,Entertainment/public assembly,19619,1914.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
145913,1444,0,2016-10-18 18:00:00,8.425,15,Entertainment/public assembly,19619,1914.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
145914,1445,0,2016-01-01 02:00:00,5.125,15,Education,4298,1970.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
145915,1445,0,2016-01-10 20:00:00,5.525,15,Education,4298,1970.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146006,1448,0,2016-11-22 21:00:00,3.100,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146007,1448,0,2016-11-30 02:00:00,3.375,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146008,1448,0,2016-12-08 08:00:00,4.275,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146009,1448,0,2016-12-16 23:00:00,3.125,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146010,1448,0,2016-12-18 23:00:00,3.775,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1

In [68]:
import os 
os.getcwd()

'c:\\Users\\leepa\\Documents\\data_center_energy_prediction\\notebooks'

In [69]:
df.to_csv('c:/Users/leepa/Documents/data_center_energy_prediction/data/processed/final_dataset.csv',index=False)

In [70]:
df.isna().sum()

building_id           0
meter                 0
timestamp             0
meter_reading         0
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
dtype: int64